//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_RTGPMC {
        displayName = "Raider Tactical Group";
        side = 1;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\LivoniaLooters_CA.paa";
        priority = 1;
    };
};

class CfgGroups {
    class WEST {

        class B_RTGPMC {
            name = "Raider Tactical Group";

            class Infantry {
                name = "Infantry";

                class b_rtgpmc_infantry_raider_team {
                    name = "Raider Team";
                    side = 1;
                    faction = "B_RTGPMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                };

                class b_rtgpmc_infantry_bulwark_team {
                    name = "Bulwark Team";
                    side = 1;
                    faction = "B_RTGPMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                };

                class b_rtgpmc_infantry_phoenix_team {
                    name = "Phoenix Team";
                    side = 1;
                    faction = "B_RTGPMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                };

                class b_rtgpmc_infantry_raider_command_team {
                    name = "Raider Command Team";
                    side = 1;
                    faction = "B_RTGPMC";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_RTGPMC_Contractor_UnArmed_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_Heli_light_03_unarmed_F;
    class I_Heli_light_03_unarmed_F_OCimport_01 : I_Heli_light_03_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_unarmed_F_OCimport_02 : I_Heli_light_03_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class B_Soldier_unarmed_F;
    class B_Soldier_unarmed_F_OCimport_01 : B_Soldier_unarmed_F { scope = 0; class EventHandlers; };
    class B_Soldier_unarmed_F_OCimport_02 : B_Soldier_unarmed_F_OCimport_01 { class EventHandlers; };

    class UK3CB_BAF_Husky_Passenger_GPMG_Green;
    class UK3CB_BAF_Husky_Passenger_GPMG_Green_OCimport_01 : UK3CB_BAF_Husky_Passenger_GPMG_Green { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_Husky_Passenger_GPMG_Green_OCimport_02 : UK3CB_BAF_Husky_Passenger_GPMG_Green_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class L7A2_1_Turret;
            class CommanderTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class UK3CB_BAF_LandRover_WMIK_Milan_Green_A;
    class UK3CB_BAF_LandRover_WMIK_Milan_Green_A_OCimport_01 : UK3CB_BAF_LandRover_WMIK_Milan_Green_A { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_LandRover_WMIK_Milan_Green_A_OCimport_02 : UK3CB_BAF_LandRover_WMIK_Milan_Green_A_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class GPMG_Turret;
            class Milan_Turret;
        };
    };

    class UK3CB_BAF_Husky_Passenger_GMG_Green;
    class UK3CB_BAF_Husky_Passenger_GMG_Green_OCimport_01 : UK3CB_BAF_Husky_Passenger_GMG_Green { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_Husky_Passenger_GMG_Green_OCimport_02 : UK3CB_BAF_Husky_Passenger_GMG_Green_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class L134A1_1_Turret;
            class CommanderTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class B_Slingload_01_Ammo_F;
    class B_Slingload_01_Ammo_F_OCimport_01 : B_Slingload_01_Ammo_F { scope = 0; class EventHandlers; };
    class B_Slingload_01_Ammo_F_OCimport_02 : B_Slingload_01_Ammo_F_OCimport_01 { scope = 0; class EventHandlers; };

    class B_Slingload_01_Cargo_F;
    class B_Slingload_01_Cargo_F_OCimport_01 : B_Slingload_01_Cargo_F { scope = 0; class EventHandlers; };
    class B_Slingload_01_Cargo_F_OCimport_02 : B_Slingload_01_Cargo_F_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_BAF_RHIB_GPMG;
    class UK3CB_BAF_RHIB_GPMG_OCimport_01 : UK3CB_BAF_RHIB_GPMG { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_RHIB_GPMG_OCimport_02 : UK3CB_BAF_RHIB_GPMG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class L7A2_1_Turret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
        };
    };

    class B_Slingload_01_Fuel_F;
    class B_Slingload_01_Fuel_F_OCimport_01 : B_Slingload_01_Fuel_F { scope = 0; class EventHandlers; };
    class B_Slingload_01_Fuel_F_OCimport_02 : B_Slingload_01_Fuel_F_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_BAF_MAN_HX58_Transport_Green;
    class UK3CB_BAF_MAN_HX58_Transport_Green_OCimport_01 : UK3CB_BAF_MAN_HX58_Transport_Green { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_MAN_HX58_Transport_Green_OCimport_02 : UK3CB_BAF_MAN_HX58_Transport_Green_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopCover_Turret;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
            class CargoTurret_09;
            class CargoTurret_10;
            class CargoTurret_11;
            class CargoTurret_12;
            class CargoTurret_13;
            class CargoTurret_14;
            class CargoTurret_15;
            class CargoTurret_16;
            class CargoTurret_17;
            class CargoTurret_18;
            class CargoTurret_19;
            class CargoTurret_20;
            class CargoTurret_21;
        };
    };

    class UK3CB_BAF_MAN_HX58_Repair_Green;
    class UK3CB_BAF_MAN_HX58_Repair_Green_OCimport_01 : UK3CB_BAF_MAN_HX58_Repair_Green { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_MAN_HX58_Repair_Green_OCimport_02 : UK3CB_BAF_MAN_HX58_Repair_Green_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopCover_Turret;
        };
    };

    class UK3CB_BAF_MAN_HX58_Fuel_Green;
    class UK3CB_BAF_MAN_HX58_Fuel_Green_OCimport_01 : UK3CB_BAF_MAN_HX58_Fuel_Green { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_MAN_HX58_Fuel_Green_OCimport_02 : UK3CB_BAF_MAN_HX58_Fuel_Green_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopCover_Turret;
        };
    };

    class CUP_B_CH47F_VIV_USA;
    class CUP_B_CH47F_VIV_USA_OCimport_01 : CUP_B_CH47F_VIV_USA { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_CH47F_VIV_USA_OCimport_02 : CUP_B_CH47F_VIV_USA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class RightDoorGun;
            class CopilotTurret;
        };
    };

    class vtx_MH60M_DAP;
    class vtx_MH60M_DAP_OCimport_01 : vtx_MH60M_DAP { scope = 0; class EventHandlers; class Turrets; };
    class vtx_MH60M_DAP_OCimport_02 : vtx_MH60M_DAP_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_10;
            class CargoTurret_11;
            class CargoTurret_14;
            class CargoTurret_15;
        };
    };

    class vtx_MH60M;
    class vtx_MH60M_OCimport_01 : vtx_MH60M { scope = 0; class EventHandlers; class Turrets; };
    class vtx_MH60M_OCimport_02 : vtx_MH60M_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_10;
            class CargoTurret_11;
            class CargoTurret_14;
            class CargoTurret_15;
        };
    };

    class I_Heli_light_03_dynamicLoadout_F;
    class I_Heli_light_03_dynamicLoadout_F_OCimport_01 : I_Heli_light_03_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_dynamicLoadout_F_OCimport_02 : I_Heli_light_03_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class UK3CB_BAF_MAN_HX58_Cargo_Green_A;
    class UK3CB_BAF_MAN_HX58_Cargo_Green_A_OCimport_01 : UK3CB_BAF_MAN_HX58_Cargo_Green_A { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_MAN_HX58_Cargo_Green_A_OCimport_02 : UK3CB_BAF_MAN_HX58_Cargo_Green_A_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopCover_Turret;
        };
    };

    class B_SDV_01_F;
    class B_SDV_01_F_OCimport_01 : B_SDV_01_F { scope = 0; class EventHandlers; class Turrets; };
    class B_SDV_01_F_OCimport_02 : B_SDV_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderTurret;
        };
    };

    class B_Slingload_01_Medevac_F;
    class B_Slingload_01_Medevac_F_OCimport_01 : B_Slingload_01_Medevac_F { scope = 0; class EventHandlers; };
    class B_Slingload_01_Medevac_F_OCimport_02 : B_Slingload_01_Medevac_F_OCimport_01 { scope = 0; class EventHandlers; };

    class B_Slingload_01_Repair_F;
    class B_Slingload_01_Repair_F_OCimport_01 : B_Slingload_01_Repair_F { scope = 0; class EventHandlers; };
    class B_Slingload_01_Repair_F_OCimport_02 : B_Slingload_01_Repair_F_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_BAF_LandRover_Hard_FFR_Green_A;
    class UK3CB_BAF_LandRover_Hard_FFR_Green_A_OCimport_01 : UK3CB_BAF_LandRover_Hard_FFR_Green_A { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_LandRover_Hard_FFR_Green_A_OCimport_02 : UK3CB_BAF_LandRover_Hard_FFR_Green_A_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class Passenger_Turret;
        };
    };

    class B_Quadbike_01_F;
    class B_Quadbike_01_F_OCimport_01 : B_Quadbike_01_F { scope = 0; class EventHandlers; };
    class B_Quadbike_01_F_OCimport_02 : B_Quadbike_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A;
    class UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_OCimport_01 : UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_OCimport_02 : UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class GPMG_Turret;
            class GPMG_2_Turret;
        };
    };

    class B_AFV_Wheeled_01_up_cannon_F;
    class B_AFV_Wheeled_01_up_cannon_F_OCimport_01 : B_AFV_Wheeled_01_up_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class B_AFV_Wheeled_01_up_cannon_F_OCimport_02 : B_AFV_Wheeled_01_up_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A;
    class UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_OCimport_01 : UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_OCimport_02 : UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class GPMG_Turret;
            class GMG_Turret;
        };
    };

    class B_UAV_01_F;
    class B_UAV_01_F_OCimport_01 : B_UAV_01_F { scope = 0; class EventHandlers; class Turrets; };
    class B_UAV_01_F_OCimport_02 : B_UAV_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_cannon_F;
    class I_LT_01_cannon_F_OCimport_01 : I_LT_01_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_cannon_F_OCimport_02 : I_LT_01_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_AT_F;
    class I_LT_01_AT_F_OCimport_01 : I_LT_01_AT_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_AT_F_OCimport_02 : I_LT_01_AT_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class MELB_AH6M;
    class MELB_AH6M_OCimport_01 : MELB_AH6M { scope = 0; class EventHandlers; class Turrets; };
    class MELB_AH6M_OCimport_02 : MELB_AH6M_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class MELB_MH6M;
    class MELB_MH6M_OCimport_01 : MELB_MH6M { scope = 0; class EventHandlers; class Turrets; };
    class MELB_MH6M_OCimport_02 : MELB_MH6M_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
            class CargoTurret_08;
        };
    };

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };


    class B_RTGPMC_Lynx_Transport_02 : I_Heli_light_03_unarmed_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lynx Transport";
        side = 1;
        faction = "B_RTGPMC";
        crew = "I_helipilot_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Contractor_UnArmed_01 : B_Soldier_unarmed_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Contractor UnArmed";
        side = 1;
        faction = "B_RTGPMC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "CUP_U_O_RUS_Gorka_Green";

        linkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","CUP_H_PMC_Cap_Grey","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr_noflag_F","CUP_H_PMC_Cap_Grey","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_U_O_RUS_Gorka_Green",{{"FirstAidKit",1}}},{"V_PlateCarrier1_rgr_noflag_F",{}},{},"CUP_H_PMC_Cap_Grey","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Husky_Passenger_GPMG_Green_01 : UK3CB_BAF_Husky_Passenger_GPMG_Green_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Husky Passenger GPMG (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class L7A2_1_Turret : L7A2_1_Turret { gunnerType = ""; };
            class CommanderTurret : CommanderTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Land_Rover_WMIK_Milan_Green_01 : UK3CB_BAF_LandRover_WMIK_Milan_Green_A_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover WMIK Milan (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class GPMG_Turret : GPMG_Turret { gunnerType = ""; };
            class Milan_Turret : Milan_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Husky_Passenger_GMG_Green_01 : UK3CB_BAF_Husky_Passenger_GMG_Green_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Husky Passenger GMG (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class L134A1_1_Turret : L134A1_1_Turret { gunnerType = ""; };
            class CommanderTurret : CommanderTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Huron_Ammo_Container_01 : B_Slingload_01_Ammo_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Huron Ammo Container";
        side = 3;
        faction = "B_RTGPMC";
        crew = "Civilian";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Huron_Cargo_Container_01 : B_Slingload_01_Cargo_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Huron Cargo Container";
        side = 3;
        faction = "B_RTGPMC";
        crew = "Civilian";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Offshore_Raiding_Craft_GPMG_01 : UK3CB_BAF_RHIB_GPMG_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offshore Raiding Craft GPMG";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class L7A2_1_Turret : L7A2_1_Turret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Huron_Fuel_Container_01 : B_Slingload_01_Fuel_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Huron Fuel Container";
        side = 3;
        faction = "B_RTGPMC";
        crew = "Civilian";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_MAN_HX58_6x6_Transport_Green_01 : UK3CB_BAF_MAN_HX58_Transport_Green_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MAN HX58 6x6 Transport (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class TopCover_Turret : TopCover_Turret { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
            class CargoTurret_09 : CargoTurret_09 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
            class CargoTurret_11 : CargoTurret_11 { gunnerType = ""; };
            class CargoTurret_12 : CargoTurret_12 { gunnerType = ""; };
            class CargoTurret_13 : CargoTurret_13 { gunnerType = ""; };
            class CargoTurret_14 : CargoTurret_14 { gunnerType = ""; };
            class CargoTurret_15 : CargoTurret_15 { gunnerType = ""; };
            class CargoTurret_16 : CargoTurret_16 { gunnerType = ""; };
            class CargoTurret_17 : CargoTurret_17 { gunnerType = ""; };
            class CargoTurret_18 : CargoTurret_18 { gunnerType = ""; };
            class CargoTurret_19 : CargoTurret_19 { gunnerType = ""; };
            class CargoTurret_20 : CargoTurret_20 { gunnerType = ""; };
            class CargoTurret_21 : CargoTurret_21 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_MAN_HX58_6x6_Repair_Green_01 : UK3CB_BAF_MAN_HX58_Repair_Green_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MAN HX58 6x6 Repair (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class TopCover_Turret : TopCover_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_MAN_HX58_6x6_Fuel_Green_01 : UK3CB_BAF_MAN_HX58_Fuel_Green_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MAN HX58 6x6 Fuel (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class TopCover_Turret : TopCover_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_CH_47_Transport_01 : CUP_B_CH47F_VIV_USA_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "CH-47 Transport";
        side = 1;
        faction = "B_RTGPMC";
        crew = "CUP_B_US_Pilot";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
            class RightDoorGun : RightDoorGun { gunnerType = ""; };
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'cup\airvehicles\cup_airvehicles_ch47\data\ch47_ext_1_baf_co.paa'];_unit setObjectTextureGlobal [1,'cup\airvehicles\cup_airvehicles_ch47\data\ch47_ext_2_baf_co.paa'];_unit setObjectTextureGlobal [2,''];_unit setObjectTextureGlobal [3,'cup\airvehicles\cup_airvehicles_ch47\data\ch47_ext_mlod_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "BAF";

    };

    class B_RTGPMC_MH_60M_DAP_01 : vtx_MH60M_DAP_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-60M DAP";
        side = 1;
        faction = "B_RTGPMC";
        crew = "vtx_uh60_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
            class CargoTurret_11 : CargoTurret_11 { gunnerType = ""; };
            class CargoTurret_14 : CargoTurret_14 { gunnerType = ""; };
            class CargoTurret_15 : CargoTurret_15 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_MH_60M_01 : vtx_MH60M_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-60M";
        side = 1;
        faction = "B_RTGPMC";
        crew = "vtx_uh60_pilot";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class MainTurret : MainTurret { gunnerType = "B_RTGPMC_Crew_Chief_01"; };
            class RightDoorGun : RightDoorGun { gunnerType = "vtx_uh60_doorgunner"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_10 : CargoTurret_10 { gunnerType = ""; };
            class CargoTurret_11 : CargoTurret_11 { gunnerType = ""; };
            class CargoTurret_14 : CargoTurret_14 { gunnerType = ""; };
            class CargoTurret_15 : CargoTurret_15 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Lynx_Armed_01 : I_Heli_light_03_dynamicLoadout_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Lynx Armed";
        side = 1;
        faction = "B_RTGPMC";
        crew = "I_helipilot_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_EPB\Heli_Light_03\data\Heli_Light_03_base_CO.paa'];_unit setObjectTextureGlobal [1,'a3\weapons_f\ammoboxes\data\ammobox_co.paa'];_unit setObjectTextureGlobal [2,'a3\weapons_f\ammoboxes\data\ammobox_signs_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class B_RTGPMC_MAN_HX58_6x6_Cargo_Empty_Green_01 : UK3CB_BAF_MAN_HX58_Cargo_Green_A_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MAN HX58 6x6 Cargo Empty (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class TopCover_Turret : TopCover_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_SDV_01 : B_SDV_01_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "SDV";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_diver_F";

        class Turrets : Turrets {
            class CommanderTurret : CommanderTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Huron_Medical_Container_01 : B_Slingload_01_Medevac_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Huron Medical Container";
        side = 3;
        faction = "B_RTGPMC";
        crew = "Civilian";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Huron_Repair_Container_01 : B_Slingload_01_Repair_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Huron Repair Container";
        side = 3;
        faction = "B_RTGPMC";
        crew = "Civilian";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Land_Rover_HardTop_FFR_Green_01 : UK3CB_BAF_LandRover_Hard_FFR_Green_A_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover HardTop FFR (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class Passenger_Turret : Passenger_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Quad_Bike_01 : B_Quadbike_01_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Quad Bike";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Land_Rover_WMIK_GPMG_FFR_Green_01 : UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover WMIK GPMG FFR (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class GPMG_Turret : GPMG_Turret { gunnerType = ""; };
            class GPMG_2_Turret : GPMG_2_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Rooikat_120_UP_01 : B_AFV_Wheeled_01_up_cannon_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rooikat 120 UP";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_crew_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'a3\Armor_F_Tank\AFV_Wheeled_01\data\afv_wheeled_01_EXT1_green_CO.paa'];_unit setObjectTextureGlobal [1,'a3\Armor_F_Tank\AFV_Wheeled_01\data\afv_wheeled_01_EXT2_green_CO.paa'];_unit setObjectTextureGlobal [2,'a3\Armor_F_Tank\AFV_Wheeled_01\data\afv_wheeled_01_wheel_green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\Armor_F_Tank\AFV_Wheeled_01\Data\afv_wheeled_01_EXT3_CO.paa'];_unit setObjectTextureGlobal [4,'a3\Armor_F_Tank\AFV_Wheeled_01\data\afv_commander_tow_CO.paa'];_unit setObjectTextureGlobal [5,'a3\Armor_F\Data\camonet_NATO_Green_CO.paa'];_unit setObjectTextureGlobal [6,'A3\Armor_F_Tank\AFV_Wheeled_01\Data\afv_wheeled_01_EXT3_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class B_RTGPMC_Land_Rover_WMIK_GMG_FFR_Green_01 : UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Land Rover WMIK GMG FFR (Green)";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Soldier_F";

        class Turrets : Turrets {
            class GPMG_Turret : GPMG_Turret { gunnerType = ""; };
            class GMG_Turret : GMG_Turret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_AR_2Darter_01 : B_UAV_01_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "AR-2 Darter";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_UAV_AI";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Wiesel_2Cannon_01 : I_LT_01_cannon_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 Cannon";
        side = 1;
        faction = "B_RTGPMC";
        crew = "I_crew_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_cannon_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class B_RTGPMC_Wiesel_2ATGM_01 : I_LT_01_AT_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 ATGM";
        side = 1;
        faction = "B_RTGPMC";
        crew = "I_crew_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_at_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class B_RTGPMC_MELB_Armed_01 : MELB_AH6M_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MELB Armed";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Helipilot_F";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_MELB_Transport_01 : MELB_MH6M_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "MELB Transport";
        side = 1;
        faction = "B_RTGPMC";
        crew = "B_Helipilot_F";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
            class CargoTurret_08 : CargoTurret_08 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_RTGPMC_Contractor_Armed_01 : B_Soldier_F_OCimport_02 {
        author = "Shrike";
        scope = 2;
        scopeCurator = 2;
        displayName = "Contractor Armed";
        side = 1;
        faction = "B_RTGPMC";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "USP_G3C_CU_KP_MC";

        linkedItems[] = {"V_PlateCarrier1_rgr","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles"};
        respawnlinkedItems[] = {"V_PlateCarrier1_rgr","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles"};

        weapons[] = {"ACWP_M4A5_145_troy_AFG_BLK","hgun_P07_F"};
        respawnWeapons[] = {"ACWP_M4A5_145_troy_AFG_BLK","hgun_P07_F"};

        magazines[] = {"hlc_30rnd_556x45_M_PMAG","16Rnd_9x21_Mag","hlc_30rnd_556x45_M_PMAG","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"hlc_30rnd_556x45_M_PMAG","16Rnd_9x21_Mag","hlc_30rnd_556x45_M_PMAG","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"ACWP_M4A5_145_troy_AFG_BLK","","optic_MRCO","WMLX_L_PEQ_R_IR_black",{"hlc_30rnd_556x45_M_PMAG",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"USP_G3C_CU_KP_MC",{{"FirstAidKit",1},{"30Rnd_65x39_caseless_mag",2,30}}},{"V_PlateCarrier1_rgr",{{"30Rnd_65x39_caseless_mag",7,30},{"16Rnd_9x21_Mag",2,17},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{},"H_HelmetB","G_Combat",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};